on: push
name: Example Workflow
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v9
        with:
          accessToken: api-9f6747c4-a376-4b0d-a5ed-3591993e1ea2
          projKey: sdk-8808153c-46bc-4a75-a6e2-8fe0528f0c71
